DROP TABLE COMMANDES;
DROP TABLE EMPLOYES ;
DROP TABLE CLIENTS ;
purge recyclebin ;

CREATE TABLE CLIENTS  (
   CODE_CLIENT          CHAR(5)        NOT NULL,
   SOCIETE              VARCHAR2(40)   NOT NULL,
   VILLE                VARCHAR2(30)   NOT NULL,
   PAYS                 VARCHAR2(15)   NOT NULL,
   CONSTRAINT CLIENTS_PK PRIMARY KEY (CODE_CLIENT)
);

CREATE TABLE EMPLOYES (NO_EMPLOYE NUMBER(2) PRIMARY KEY, 
                       NOM VARCHAR2(20) NOT NULL, 
                       PRENOM VARCHAR2(20) NOT NULL, 
                       TITLE  NUMBER(1) DEFAULT 1 CHECK ( TITLE BETWEEN 1 AND 3) ,
                       DATE_EMBAUCHE DATE DEFAULT SYSDATE,                       
                       SALAIRE NUMBER(8,2) NOT NULL, 
                       COMMISSION NUMBER(4,2)); 

CREATE TABLE COMMANDES  (
   NO_COMMANDE          NUMBER(6)                       NOT NULL,
   CODE_CLIENT          CHAR(5)                         NOT NULL,
   NO_EMPLOYE           NUMBER(6)                       NOT NULL,
   DATE_COMMANDE        DATE                            NOT NULL,
   DATE_ENVOI           DATE,
   PORT                 NUMBER(8,2),
   CONSTRAINT COMMANDES_PK PRIMARY KEY (NO_COMMANDE)
);

ALTER TABLE COMMANDES
	ADD CONSTRAINT COMMANDES_UK UNIQUE ( CODE_CLIENT, DATE_COMMANDE);

ALTER TABLE COMMANDES
   ADD CONSTRAINT COMM_EMPL_FK FOREIGN KEY (NO_EMPLOYE)
      REFERENCES EMPLOYES (NO_EMPLOYE);

ALTER TABLE COMMANDES
   ADD CONSTRAINT COMM_CLIE_FK FOREIGN KEY (CODE_CLIENT)
      REFERENCES CLIENTS (CODE_CLIENT);      

DESC EMPLOYES 
              
INSERT INTO EMPLOYES (NO_EMPLOYE, NOM, PRENOM, TITLE, DATE_EMBAUCHE, SALAIRE, COMMISSION)  
VALUES (1, 'BIZOI', 'Razvan', 1, default, 1250.50, null);

INSERT INTO EMPLOYES (NO_EMPLOYE, NOM, PRENOM, TITLE, DATE_EMBAUCHE, SALAIRE, COMMISSION) 
VALUES (2, 'BIZOI', 'Radu', 1, default, 2500.50, null);

SELECT * FROM EMPLOYES;


SELECT TABLE_NAME,
       COLUMN_NAME ,
       DATA_TYPE,
       DATA_LENGTH,
       DATA_PRECISION,       
       NULLABLE
FROM USER_TAB_COLUMNS
ORDER BY TABLE_NAME,COLUMN_ID;

SELECT UC_R.TABLE_NAME,
       UCC_R.COLUMN_NAME,
       UC_R.CONSTRAINT_TYPE,
       DECODE(UC_R.CONSTRAINT_TYPE,'P','PK-Clé Primaire',
                                   'R', 'FK-Clé Étrangère',
                                   'C','CHECK', 
                                   'U', 'Clé Unique', 'autre') TYPE,
       UC_R.SEARCH_CONDITION 
FROM USER_CONSTRAINTS UC_R
     JOIN USER_CONS_COLUMNS UCC_R
        ON UCC_R.CONSTRAINT_NAME = UC_R.CONSTRAINT_NAME
ORDER BY UC_R.TABLE_NAME, TYPE DESC, UCC_R.POSITION;